Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "nginx" do |nginx|
    nginx.vm.hostname = "nginx"
    nginx.vm.provision "shell", inline: <<-SHELL
          yum update -y
          yum install epel-release -y
          yum install vim nginx policycoreutils-python setroubleshoot -y # Ставим нужные утилиты для работы с selinux
          sed -i 's/80/8089/' /etc/nginx/nginx.conf # Меняем порт nginx
          semanage port -a -t http_port_t -p tcp 8089 # Добовляем не стондартный порт ( посмотрет можно так semanage port -l | grep http_port_t)
          systemctl start nginx.service
          SHELL
  end

 end
