---
# tasks file for nginx
- name: Install epel-release
  yum:
    name: epel-release
    state: latest
  tags:
    -epel-package
    -packages
   
- name: NGINX | Install NGINX package from EPEL Repo
  yum:
     name: nginx
     state: latest
  notify: restart nginx
  tags:
    -nginx-package
    -packages
- name:
  yum:
    name: vim
    state: latest
  tags:
    -package
    -vim
- name: NGINX | Create NGINX config file from template
  template:
     src: templates/nginx.conf.j2
     dest: /etc/nginx/nginx.conf
  notify: reload nginx
  tags:
    -nginx-configuration
