version: '3.7'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"  
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php-network
  php:
    build:
      context: ./php 
    volumes: 
      - ./code:/code
    networks:
      - php-network

networks:
  php-network:
    driver: bridge
