# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
             v.memory = 1024
  end

  config.vm.define "backup" do |backup|   
    backup.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "int"
    backup.vm.hostname = "backup"
    backup.vm.provision "shell", inline: <<-SHELL
            yum install epel-release -y
            yum install vim mc borgbackup -y
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
            useradd -m borg && mkdir ~borg/.ssh
            chown -R borg:borg /home/borg/.ssh
            echo "borg" | passwd --stdin borg
            SHELL
  end

  config.vm.define "server" do |server|
    server.vm.network "private_network", ip: "192.168.50.15", virtualbox__intnet: "int"
    server.vm.hostname = "server"
    server.vm.provision "file", source: "borgbackup.sh", destination: "~/borgbackup.sh"
    server.vm.provision "shell", path: "server.sh"
    server.vm.provision "shell", inline: <<-SHELL
            systemctl start postgresql   
            SHELL
  end

end
