# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",

        :ip_addr => '192.168.11.110',
	:disks => {
		        :sata1 => {
			            :dfile => './sata1.vdi',
		          	    :size => 4096,
			            :port => 1
		         },

        }

		
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
          config.vm.define boxname do |box|
          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "2048"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  config.vm.provision "file", source: "files.tar.xz", destination: "/home/vagrant/"
    config.vm.provision "file", source: "mkdir.sh", destination: "/home/vagrant/"
    box.vm.provision "shell", inline: <<-SHELL
	      sudo su
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh 
          sed -i s/^SELINUX=.*$/SELINUX=permissive/ /etc/selinux/config
          setenforce 0
          yum update -y
          yum install epel-release -y
          yum install vim mc wget -y
          yum install epel-release -y && yum install spawn-fcgi php php-cli mod_fcgid httpd -y
          wget https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-8.4.1-x64.bin
          chmod +x atlassian-jira-software-8.4.1-x64.bin
          SHELL
        end
      end
  end

