# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # Configure VM
   config.vm.define "elk" do |elk|
    elk.vm.box = "bento/ubuntu-16.04"
    elk.ssh.insert_key = false
    elk.vm.network "public_network"
    elk.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "dns"


    # Configure provisioning
    elk.vm.provision "file", source: "provision", destination: "/vagrant"
    elk.vm.provision "shell", path: "bootstrap.sh"
    elk.vm.provision "shell", inline: <<-SHELL
            systemctl restart logstash
            systemctl restart elasticsearch 
            systemctl restart kibana
            SHELL

    # Configure network ports
    #elk.vm.network "forwarded_port", host: 9200, guest: 9200 # Elasticsearch (http)
    #elk.vm.network "forwarded_port", host: 9300, guest: 9300 # Elasticsearch (transport)
    #elk.vm.network "forwarded_port", host: 5601, guest: 5601 # Kibana
    #elk.vm.network "forwarded_port", host: 5044, guest: 5044 # Logstash
 end
    # Configure Virtualbox
    config.vm.provider "virtualbox" do |vb, override| 
        vb.cpus = 1
        vb.memory = 4096
        vb.gui = false
        vb.name = "elk"
    end
    
    config.vm.define "web" do |web|
        web.vm.box = "centos/7"
        web.vm.network "public_network"
        web.vm.network "private_network", ip: "192.168.50.13", virtualbox__intnet: "dns"
        web.vm.hostname = "web"
        web.vm.provider :virtualbox do |vb|
              vb.name = "web"
              vb.customize ["modifyvm", :id, "--memory", "512"]
        web.vm.provision "file", source: "provision", destination: "/vagrant"
        web.vm.provision "shell", path: "filebeats.sh"
        web.vm.provision "shell", inline: <<-SHELL
            systemctl restart nginx 
            systemctl restart filebeats
            filebeat modules enable auditd
            SHELL
       end
   end
end

