# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :host1 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150'
},
}
Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
            # Подключаем дополнительные диски
            #vb.customize ['createhd', '--filename', second_disk, '--format', 'VDI', '--size', 5 * 1024]
            #vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 0, '--device', 1, '--type', 'hdd', '--medium', second_disk]
          end
          config.vm.provision "file", source: "test_login.sh", destination: "/home/vagrant/"
          box.vm.provision "shell", inline: <<-SHELL
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            systemctl restart sshd
            sudo sudo setenforce 0
            echo "1234" | passwd root --stdin
            chmod +x test_login.sh
            cp /home/vagrant/test_login.sh /usr/local/bin/
            sudo useradd day &&  sudo useradd test
            echo "2019"|sudo passwd --stdin day && echo "2019" | sudo passwd --stdin test
            sudo groupadd admin && sudo gpasswd -M day,test admin
            cd /etc/security
            echo -e '*;*;test;!Tu' >> time.conf
            cd /etc/pam.d/
            sed -i "2i account required  pam_exec.so /usr/local/bin/test_login.sh" sshd
            sed -i "2i account  required  pam_time.so " sshd 
            echo -e "day        ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers.d/day  
            yum install vim mc -y
          SHELL
      end
  end
end

